# Generated by Django 3.1.4 on 2021-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifieddate', models.DateField(auto_now=True)),
                ('createddate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timestamp',
                'verbose_name_plural': 'Timestamps',
            },
        ),
    ]
