# Generated by Django 3.1.4 on 2021-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Models', '0002_car_truck_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
