# Generated by Django 3.1.4 on 2021-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_car_truck_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='wheel_count',
            field=models.IntegerField(),
        ),
    ]
