# Generated by Django 3.1.4 on 2021-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_auto_20210522_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='timestamp_ptr',
        ),
        migrations.AddField(
            model_name='reporter',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
