# Generated by Django 3.1.4 on 2021-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0009_auto_20210522_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='timestamp_ptr',
        ),
        migrations.AddField(
            model_name='place',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
