# Generated by Django 3.1.4 on 2021-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_auto_20210523_0901'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='Models_plac_name_d7cea6_idx'),
        ),
    ]
