# Generated by Django 3.1.4 on 2021-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0012_auto_20210523_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
