# Generated by Django 3.1.4 on 2021-05-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_auto_20210523_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TaskX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleXx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_number', models.CharField(max_length=20, unique=True)),
                ('wheel_count', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='placex',
            index=models.Index(fields=['name'], name='Models_plac_name_1a9a12_idx'),
        ),
        migrations.AddField(
            model_name='person',
            name='information',
            field=models.ManyToManyField(to='Models.InformationX'),
        ),
        migrations.AddField(
            model_name='person',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Models.placex'),
        ),
        migrations.AddField(
            model_name='person',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.taskx'),
        ),
    ]
