# Generated by Django 3.1.4 on 2021-05-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_framework_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post', 'verbose_name_plural': 'Status posts'},
        ),
    ]
